name = "get-stripe-session-status"
description = "getStripeSessionStatus function must be declared in the actor"
query = """
(source_file (obj_dec "actor" (obj_body))) @error
(source_file (class_dec "actor" (obj_body))) @error
(source_file
  (obj_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @fn
          (#eq? @fn "getStripeSessionStatus"))))))  @filter
(source_file
  (class_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @fn
          (#eq? @fn "getStripeSessionStatus"))))))  @filter
"""
