name = "no-redeclare-transform"
description = "Do NOT redeclare transform — it is provided by MixinStripe"
query = """
(source_file
  (obj_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "transform"))))))
(source_file
  (class_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "transform"))))))
"""
