name = "no-redeclare-get-stripe-session-status"
description = "Do NOT redeclare getStripeSessionStatus — it is provided by MixinStripe"
query = """
(source_file
  (obj_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "getStripeSessionStatus"))))))
(source_file
  (class_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "getStripeSessionStatus"))))))
"""
