name = "set-stripe-configuration"
description = "setStripeConfiguration function must be declared in the actor"
query = """
(source_file (obj_dec "actor" (obj_body))) @error
(source_file (class_dec "actor" (obj_body))) @error
(source_file
  (obj_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @fn
          (#eq? @fn "setStripeConfiguration"))))))  @filter
(source_file
  (class_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @fn
          (#eq? @fn "setStripeConfiguration"))))))  @filter
"""
