[package]
name = "caffeineai-user-approval"
version = "0.1.1"
description = "Approval-based user management."
license = "Apache-2.0"
repository = "https://github.com/caffeinelabs/skills"
keywords = ["motoko", "icp"]

[dependencies]
core = "2.2.0"
caffeineai-authorization = "../../authorization/backend"

[toolchain]
moc = "1.2.0"
