name = "no-redeclare-set-approval"
description = "Do NOT redeclare setApproval — it is provided by MixinUserApproval"
query = """
(source_file
  (obj_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "setApproval"))))))
(source_file
  (class_dec "actor"
    (obj_body
      (dec_field
        (func_dec
          (_) @error
          (#eq? @error "setApproval"))))))
"""
