/// Golden-fixture conformance for the segment-image producer: the images the shipped
/// JavaScript encoder (tools/oql-ingest/encode.mjs) emits, checked byte for byte
/// against `Image.build` and answer for answer through `Table.loadSegmentAt`.
///
/// The canister validates an image's STRUCTURE and trusts its footer VALUES (see the
/// trust note in `Image`), so an encoder bug loads cleanly and is served as a wrong
/// query answer. This test is what stands between the producer and that outcome.
///
/// Fixtures: `test/fixtures/SegmentImageFixture.mo`, generated by
/// `tools/oql-ingest/gen-segment-image-fixtures.mjs` together with the .bin/.json
/// pairs in `test/fixtures/segment-images/`; CI runs the generator's `--check` mode
/// so the three stay in step. Runs under PocketIC because it uses a Region.
import { test } "mo:test/async";
import Array "mo:core/Array";
import Blob "mo:core/Blob";
import Float "mo:core/Float";
import Int "mo:core/Int";
import Int64 "mo:core/Int64";
import List "mo:core/List";
import Nat "mo:core/Nat";
import Nat8 "mo:core/Nat8";
import Nat64 "mo:core/Nat64";
import Region "mo:core/Region";
import Runtime "mo:core/Runtime";
import Text "mo:core/Text";
import Cell "../src/columnar/Cell";
import Columnar "../src/columnar/Columnar";
import Image "../src/columnar/Image";
import Table "../src/Table";
import F "./fixtures/SegmentImageFixture";

actor {

  // ── Rendering, so a failure names what disagreed ─────────────────────────

  func cellText(c : ?Cell.Cell) : Text = switch c {
    case null "null";
    case (?#nat n) "#nat " # Nat64.toText(n);
    case (?#int i) "#int " # Int64.toText(i);
    case (?#float f) "#float " # Float.toText(f);
    case (?#bool b) "#bool " # (if b "true" else "false");
    case (?#text t) "#text \"" # t # "\"";
    case (?#bytes b) "#bytes of " # Nat.toText(b.size()) # " bytes";
  };

  func sumText(s : Cell.Sum) : Text = switch s {
    case (#int i) Int.toText(i);
    case (#float f) Float.toText(f);
  };

  func mismatch(fx : F.Fixture, where : Text, stat : Text, got : Text, want : Text) : Text =
    fx.name # ": " # where # ": " # stat # " is " # got # ", expected " # want;

  func fail(e : ?Text) { switch e { case null {}; case (?msg) Runtime.trap(msg) } };

  // ── Bytes ────────────────────────────────────────────────────────────────

  func le(bytes : [Nat8], off : Nat, width : Nat) : Nat {
    var v = 0;
    var i = width;
    while (i > 0) { i -= 1; v := v * 256 + Nat8.toNat(bytes[off + i]) };
    v;
  };

  func firstDiff(a : [Nat8], b : [Nat8]) : ?Nat {
    let n = Nat.min(a.size(), b.size());
    var i = 0;
    while (i < n) { if (a[i] != b[i]) return ?i; i += 1 };
    if (a.size() != b.size()) ?n else null;
  };

  func diffCount(a : [Nat8], b : [Nat8]) : Nat {
    var d = if (a.size() > b.size()) a.size() - b.size() else b.size() - a.size();
    var i = 0;
    while (i < Nat.min(a.size(), b.size())) { if (a[i] != b[i]) d += 1; i += 1 };
    d;
  };

  // Validate `image` on its own, the way `appendSegmentImageAt` does after storing it.
  func validate(fx : F.Fixture, image : [Nat8]) : { #ok : { rows : Nat; bodyLen : Nat64; cols : [{ kind : Nat8; offsetWidth : Nat8; blockOff : Nat64; blockLen : Nat64; trailerOff : Nat64 }] }; #err : Text } {
    let scratch = Region.new();
    ignore scratch.grow(1);
    let blob = Blob.fromArray(image);
    scratch.storeBlob(0, blob);
    Image.validate(scratch, 0, Nat64.fromNat(blob.size()), fx.cols);
  };

  // ── The four checks. Each answers null, or the first disagreement it found. ──

  func checkLayout(fx : F.Fixture, image : [Nat8]) : ?Text {
    let C = fx.cols.size();
    if (le(image, 0, 4) != 0x4F514C53) return ?mismatch(fx, "header", "magic", Nat.toText(le(image, 0, 4)), "0x4F514C53");
    if (le(image, 4, 2) != 1) return ?mismatch(fx, "header", "version", Nat.toText(le(image, 4, 2)), "1");
    if (le(image, 8, 4) != fx.rows.size()) return ?mismatch(fx, "header", "rows", Nat.toText(le(image, 8, 4)), Nat.toText(fx.rows.size()));
    if (le(image, 12, 2) != C) return ?mismatch(fx, "header", "ncols", Nat.toText(le(image, 12, 2)), Nat.toText(C));
    if (le(image, 24, 8) != image.size()) return ?mismatch(fx, "header", "bodyLen", Nat.toText(le(image, 24, 8)), Nat.toText(image.size()));
    if (image.size() % 8 != 0) return ?mismatch(fx, "header", "bodyLen alignment", Nat.toText(image.size() % 8), "0");

    let d = switch (validate(fx, image)) {
      case (#ok d) d;
      case (#err e) return ?(fx.name # ": Image.validate refused the image: " # e);
    };
    if (d.rows != fx.rows.size()) return ?mismatch(fx, "descriptor", "rows", Nat.toText(d.rows), Nat.toText(fx.rows.size()));
    if (d.cols.size() != fx.directory.size()) return ?mismatch(fx, "descriptor", "columns", Nat.toText(d.cols.size()), Nat.toText(fx.directory.size()));
    var c = 0;
    while (c < C) {
      let (got, want) = (d.cols[c], fx.directory[c]);
      let where = "column " # Nat.toText(c);
      if (got.kind != want.kind) return ?mismatch(fx, where, "kind", Nat8.toText(got.kind), Nat8.toText(want.kind));
      if (got.offsetWidth != want.offsetWidth) return ?mismatch(fx, where, "offsetWidth", Nat8.toText(got.offsetWidth), Nat8.toText(want.offsetWidth));
      if (Nat64.toNat(got.blockOff) != want.blockOff) return ?mismatch(fx, where, "blockOff", Nat64.toText(got.blockOff), Nat.toText(want.blockOff));
      if (Nat64.toNat(got.blockLen) != want.blockLen) return ?mismatch(fx, where, "blockLen", Nat64.toText(got.blockLen), Nat.toText(want.blockLen));
      // The stride is not in the descriptor; read it off the directory entry.
      let stride = le(image, Nat64.toNat(Image.HEADER + Image.DIRENT * Nat64.fromNat(c)) + 4, 4);
      if (stride != want.stride) return ?mismatch(fx, where, "stride", Nat.toText(stride), Nat.toText(want.stride));
      c += 1;
    };
    null;
  };

  func checkBytes(fx : F.Fixture, image : [Nat8]) : ?Text {
    let scratch = Region.new();
    let built = Blob.toArray(Image.build(scratch, fx.cols, fx.rows.size(), func (r : Nat, c : Nat) : ?Cell.Cell = fx.rows[r][c]));
    switch (firstDiff(built, image)) {
      case null null;
      case (?off) ?(fx.name # ": byte " # Nat.toText(off) # " differs between Image.build (" # Nat.toText(built.size()) # " bytes) and the producer's image (" # Nat.toText(image.size()) # " bytes)");
    };
  };

  func columnsOf(fx : F.Fixture) : [Table.Column] =
    Array.tabulate<Table.Column>(fx.cols.size(), func c = ("c" # Nat.toText(c), fx.cols[c]));

  /// Load `image` the way `ImportData.putSegment` does: into a fresh index-free table
  /// through `Table.loadSegmentAt` at row 0.
  func load(fx : F.Fixture, image : [Nat8]) : Table.Table {
    let t = Table.new(columnsOf(fx), []);
    let added = Table.loadSegmentAt(t, Blob.fromArray(image), 0);
    fail(if (added == fx.rows.size()) null else ?mismatch(fx, "loadSegmentAt", "rows added", Nat.toText(added), Nat.toText(fx.rows.size())));
    t;
  };

  func checkRows(fx : F.Fixture, t : Table.Table) : ?Text {
    let N = fx.rows.size();
    if (Table.size(t) != N) return ?mismatch(fx, "table", "size", Nat.toText(Table.size(t)), Nat.toText(N));
    if (Table.appended(t) != N) return ?mismatch(fx, "table", "appended", Nat.toText(Table.appended(t)), Nat.toText(N));
    var r = 0;
    while (r < N) {
      switch (Columnar.getRow(t.store, r)) {
        case null return ?(fx.name # ": row " # Nat.toText(r) # " is missing");
        case (?cells) {
          var c = 0;
          while (c < fx.cols.size()) {
            if (cells[c] != fx.rows[r][c]) return ?mismatch(fx, "row " # Nat.toText(r) # ", column " # Nat.toText(c), "value", cellText(cells[c]), cellText(fx.rows[r][c]));
            c += 1;
          };
        };
      };
      r += 1;
    };
    null;
  };

  func checkFooters(fx : F.Fixture, t : Table.Table) : ?Text {
    let C = fx.cols.size();
    let segments = List.size(t.store.segments);
    if (fx.rows.size() == 0) {
      // A zero-row image registers nothing; there is no footer to compare.
      if (segments != 0) return ?mismatch(fx, "table", "segments", Nat.toText(segments), "0");
      return null;
    };
    if (segments != 1) return ?mismatch(fx, "table", "segments", Nat.toText(segments), "1");
    let seg = switch (List.get(t.store.segments, 0)) { case (?g) g; case null return ?(fx.name # ": no segment") };
    var c = 0;
    while (c < C) {
      let where = "column " # Nat.toText(c);
      let (got, want) = (seg.footers[c], fx.footers[c]);
      if (got.count != want.count) return ?mismatch(fx, where, "count", Nat.toText(got.count), Nat.toText(want.count));
      if (got.nulls != want.nulls) return ?mismatch(fx, where, "nulls", Nat.toText(got.nulls), Nat.toText(want.nulls));
      if (got.min != want.min) return ?mismatch(fx, where, "min", cellText(got.min), cellText(want.min));
      if (got.max != want.max) return ?mismatch(fx, where, "max", cellText(got.max), cellText(want.max));
      if (seg.liveSum[c] != want.sum) return ?mismatch(fx, where, "sum", sumText(seg.liveSum[c]), sumText(want.sum));
      if (seg.liveCount[c] != want.count) return ?mismatch(fx, where, "live count", Nat.toText(seg.liveCount[c]), Nat.toText(want.count));
      // The served answers: these are what a query gets, straight out of the footer.
      if (Columnar.countOf(t.store, c) != want.count) return ?mismatch(fx, where, "countOf", Nat.toText(Columnar.countOf(t.store, c)), Nat.toText(want.count));
      if (Columnar.sumOf(t.store, c) != want.sum) return ?mismatch(fx, where, "sumOf", sumText(Columnar.sumOf(t.store, c)), sumText(want.sum));
      let (wantMin, wantMax) = (servedExtreme(fx, c, true), servedExtreme(fx, c, false));
      if (Columnar.minOf(t.store, c) != wantMin) return ?mismatch(fx, where, "minOf", cellText(Columnar.minOf(t.store, c)), cellText(wantMin));
      if (Columnar.maxOf(t.store, c) != wantMax) return ?mismatch(fx, where, "maxOf", cellText(Columnar.maxOf(t.store, c)), cellText(wantMax));
      c += 1;
    };
    null;
  };

  // What `minOf`/`maxOf` must answer for column `c`. A zone-mapped column answers
  // from its footer; a text column has no zone map and is scanned, so the answer is
  // the extreme of the fixture's own cells; a #bytes column has no order at all.
  func servedExtreme(fx : F.Fixture, c : Nat, wantMin : Bool) : ?Cell.Cell {
    switch (Cell.bytesWidth(fx.cols[c])) { case (?_) return null; case null {} };
    if (not Cell.isVar(fx.cols[c])) return if wantMin fx.footers[c].min else fx.footers[c].max;
    var best : ?Cell.Cell = null;
    for (row in fx.rows.values()) {
      switch (row[c], best) {
        case (null, _) {};
        case (?v, null) best := ?v;
        case (?v, ?b) if (if wantMin Cell.lt(v, b) else Cell.lt(b, v)) best := ?v;
      };
    };
    best;
  };

  // `fx.image` with bit 0 of byte `offset` flipped. Still structurally valid: the
  // canister takes it, which is why the fixture comparison has to catch it.
  func corrupt(fx : F.Fixture, offset : Nat) : [Nat8] {
    let image = Array.tabulate<Nat8>(fx.image.size(), func i = if (i == offset) fx.image[i] ^ 1 else fx.image[i]);
    assert diffCount(fx.image, image) == 1;
    assert firstDiff(fx.image, image) == ?offset;
    switch (validate(fx, image)) {
      case (#ok _) {};
      case (#err e) Runtime.trap(fx.name # " corrupted at " # Nat.toText(offset) # " was refused by Image.validate (" # e # "), so the trust gap this test covers has closed; update the test");
    };
    image;
  };

  // Column 0's trailer sits first after the directory; sumLo is 32 bytes in (see the
  // layout table in Image.mo).
  func sumOffset(fx : F.Fixture) : Nat =
    Nat64.toNat(Image.HEADER + Image.DIRENT * Nat64.fromNat(fx.cols.size())) + 32;

  // Column 0's block: the validity bitmap words, then row 1's 8-byte value.
  func row1Offset(fx : F.Fixture) : Nat =
    fx.directory[0].blockOff + 8 * ((fx.rows.size() + 63) / 64) + 8;

  func mustName(e : ?Text, needles : [Text]) {
    switch e {
      case null Runtime.trap("the corruption went unnoticed");
      case (?msg) {
        for (n in needles.values()) {
          if (not Text.contains(msg, #text n)) Runtime.trap("failure does not name '" # n # "': " # msg);
        };
      };
    };
  };

  public func runTests() : async () {
    await test("every fixture carries the header and directory markers the canister reads", func() : async () {
      for (fx in F.all.values()) fail(checkLayout(fx, fx.image));
    });

    await test("the reference encoder reproduces every fixture byte for byte", func() : async () {
      for (fx in F.all.values()) fail(checkBytes(fx, fx.image));
    });

    await test("every fixture decodes through the ImportData load path to its rows", func() : async () {
      for (fx in F.all.values()) fail(checkRows(fx, load(fx, fx.image)));
    });

    await test("every fixture's footers, zone-map bounds and served answers are the sidecar's", func() : async () {
      for (fx in F.all.values()) fail(checkFooters(fx, load(fx, fx.image)));
    });

    await test("a flipped footer statistic is accepted by the canister and caught by the footer check, naming column and statistic", func() : async () {
      let fx = F.scalars;
      let off = sumOffset(fx);
      let image = corrupt(fx, off);
      let t = load(fx, image);
      // The rows are untouched, so only the footer comparison can see this.
      fail(checkLayout(fx, image));
      fail(checkRows(fx, t));
      mustName(checkFooters(fx, t), ["column 0", "sum"]);
      mustName(checkBytes(fx, image), ["byte " # Nat.toText(off)]);
    });

    await test("a flipped payload byte is accepted by the canister and caught by the row check, naming row and column", func() : async () {
      let fx = F.scalars;
      let off = row1Offset(fx);
      let image = corrupt(fx, off);
      let t = load(fx, image);
      fail(checkLayout(fx, image));
      mustName(checkRows(fx, t), ["row 1", "column 0"]);
      mustName(checkBytes(fx, image), ["byte " # Nat.toText(off)]);
    });
  };
};
